// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "razmolodinivan@mail.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/signIn": {
            "post": {
                "description": "Метод позволяет войти в аккаунт организации, либо сотрудника.\nДля входа сотрудника требуется ` + "`" + `jwt токен` + "`" + ` соотвествующей ему огранизации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Вход для организации, либо сотрудника",
                "parameters": [
                    {
                        "type": "string",
                        "description": "` + "`" + `org` + "`" + `(default) or ` + "`" + `employee` + "`" + `",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "description": "Объект для входа в огранизацию. Обязательные поля:` + "`" + `email` + "`" + `, ` + "`" + `password` + "`" + `",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myservice.signInOrgInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Возвращает ` + "`" + `jwt токен` + "`" + ` при успешной авторизации",
                        "schema": {
                            "$ref": "#/definitions/myservice.signInOrgOutput"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/myservice.myServiceError"
                        }
                    }
                }
            }
        },
        "/auth/signUp": {
            "post": {
                "description": "Метод позволяет зарегистрировать организацию или сотрудника данной огранизации.\nРегистрация сотрудника возможна только с ` + "`" + `jwt токеном` + "`" + ` организации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Регистрация организации, либо сотрудника",
                "parameters": [
                    {
                        "type": "string",
                        "description": "` + "`" + `org` + "`" + `(default) or ` + "`" + `employee` + "`" + `",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "description": "Объект для регитсрации огранизации. Обязательные поля:` + "`" + `email` + "`" + `, ` + "`" + `password` + "`" + `",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myservice.signUpOrgInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Возвращаемый объект при регистрации огранизации",
                        "schema": {
                            "$ref": "#/definitions/myservice.signUpOrgOutput"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/myservice.myServiceError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "myservice.myServiceError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "myservice.signInOrgInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "myservice.signInOrgOutput": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "myservice.signUpOrgInput": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "myservice.signUpOrgOutput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1-alpha",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "POS-Ninja Backend API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
